name: CI/CD Weather App

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build image
      - name: Build Docker image
        run: docker build -t weather_app:latest .

      # Save image
      - name: Save Docker image
        run: docker save weather_app:latest -o weather_app.tar

      # Clean old files on EC2
      - name: Clean previous files on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            rm -rf ~/weather_app.tar

      # Copy tar file
      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: weather_app.tar
          target: ~

      # Deploy container
      - name: Deploy container on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker load -i ~/weather_app.tar
            docker stop weather_app || true
            docker rm weather_app || true
            docker run -d --name weather_app -p 80:80 weather_app:latest